name: Test secrets
on: workflow_dispatch

jobs:
  print-secret:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          echo $SUPER_SECRET
        env:
          SUPER_SECRET: ${{ secrets.SUPER_SECRET }}
